#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
url                                        : https://halovintageapp.github.io

# App Info
ios_app_id                                : 6741214523                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : br                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=br.com.halovintage                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description:
  pt: O mundo do som vintage na palma da sua mão.
  en: The world of vintage sound at your fingertips.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : HaloVintage App                                
your_link                                 :                      
your_city                                 : Curitiba - Paraná
email_address                             : halovintageapp@gmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : halovintageapp
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 

# Feature List                            Edit, add or remove features to be presented.
features:
  - title:
      pt: Encontre equipamentos de som vintage com facilidade
      en: Find vintage audio gear with ease
    description:
      pt: Navegue por marcas, categorias e décadas para descobrir aparelhos clássicos com riqueza de detalhes.
      en: Browse by brand, category, and decade to discover classic devices packed with detail.
    fontawesome_icon_name: search

  - title:
      pt: Catálogo técnico completo
      en: Comprehensive technical catalog
    description:
      pt: Acesse especificações, modelos relacionados e informações históricas de equipamentos anteriores aos anos 90.
      en: Access specifications, related models, and historical insights for equipment built before the 1990s.
    fontawesome_icon_name: book

  - title:
      pt: Design retrô com tecnologia moderna
      en: Retro design with modern tech
    description:
      pt: Interface elegante e intuitiva, inspirada na estética vintage, mas com performance atual.
      en: Enjoy an elegant, intuitive interface inspired by vintage aesthetics yet powered by modern performance.
    fontawesome_icon_name: palette

  - title:
      pt: Atualizações frequentes
      en: Frequent updates
    description:
      pt: Novos modelos e marcas adicionados constantemente para manter o acervo sempre em crescimento.
      en: New models and brands are added regularly to keep the collection growing.
    fontawesome_icon_name: sync

  - title:
      pt: Referência para restauração e pesquisa
      en: Reference for restoration and research
    description:
      pt: Uma fonte confiável para colecionadores, técnicos e apaixonados por áudio vintage.
      en: A trusted source for collectors, technicians, and vintage audio enthusiasts alike.
    fontawesome_icon_name: tools

  - title:
      pt: Feito por entusiastas, para entusiastas
      en: Made by enthusiasts, for enthusiasts
    description:
      pt: Criado com cuidado por quem ama som analógico — ideal para preservar a história do áudio.
      en: Crafted by people who love analog sound—perfect for preserving audio history.
    fontawesome_icon_name: heart


footer_text:
  made_by:
    pt: Feito por
    en: Made by
  located_in:
    pt: em
    en: in
  press_kit:
    pt: Kit de imprensa
    en: Press Kit

# Theme Settings
topbar_color                              : "#ffe3b2"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#85480b"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#85480b"
feature_icons_background_color            : "#ffe3b2"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

include:
  - .well-known

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-multiple-languages-plugin

# o18y
languages: ["pt", "en"]
default_lang: "pt"
